---
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    # enable Hubble UI
    enabled: true
    standalone:
      # enable Hubble UI standalone deployment
      enabled: true
    ingress:
      enabled: true
      hosts:
        - hubble.127.0.0.1.nip.io
