---
operator:
  replicas: 1
  prometheus:
    enabled: true
nodeinit:
  enabled: true
kubeProxyReplacement: partial
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
bpf:
  masquerade: false
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
prometheus:
  enabled: true

