apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kiosk-cluster-autoscaler-status-{{ .Values.userNamespace }}
  labels:
    {{- include "ondemand-user-permissions.labels" . | nindent 4 }}
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-autoscaler-status
    verbs:
      - get
      - list
