apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kiosk-cluster-autoscaler-status-{{ .Values.userNamespace }}
  labels:
    {{- include "ondemand-user-permissions.labels" . | nindent 4 }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kiosk-cluster-autoscaler-status-{{ .Values.userNamespace }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.userName }}
